--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.22.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 20/01/2023 3:14:42 pm
-- Server version: 5.5.5-10.4.27-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE gicalde_db;

--
-- Drop table `users`
--
DROP TABLE IF EXISTS users;

--
-- Set default database
--
USE gicalde_db;

--
-- Create table `users`
--
CREATE TABLE users (
  id int(11) NOT NULL AUTO_INCREMENT,
  code varchar(255) DEFAULT NULL,
  username varchar(255) DEFAULT NULL,
  password varchar(255) DEFAULT NULL,
  role_id int(11) DEFAULT NULL,
  activation_code varchar(255) DEFAULT NULL,
  first_name varchar(255) DEFAULT NULL,
  middle_name varchar(255) DEFAULT NULL,
  last_name varchar(255) DEFAULT NULL,
  dob date DEFAULT NULL,
  gender varchar(255) DEFAULT NULL,
  contact_no varchar(255) DEFAULT NULL,
  address varchar(255) DEFAULT NULL,
  is_activated int(1) DEFAULT NULL,
  created_by int(11) DEFAULT NULL,
  created_at datetime DEFAULT CURRENT_TIMESTAMP (),
  updated_by int(11) DEFAULT NULL,
  updated_at datetime DEFAULT NULL,
  deleted_by int(11) DEFAULT NULL,
  deleted_at datetime DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

-- 
-- Dumping data for table users
--
INSERT INTO users VALUES
(1, '1', 'admin@mail.com', '$2y$10$syv23bvpa0ujAz6Piz5Ob.QEfuG8kKv43fthNKwBJgkj2NZ8nAuvK', 1, NULL, 'ADMINISTRATOR', NULL, 'ADMINISTRATOR', '2023-01-20', 'MALE', '09958242310', 'ROXAS CITY, CAPIZ', 1, 1, '2023-01-20 07:26:23', NULL, NULL, NULL, NULL);

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;