--
-- Script was generated by Devart dbForge Studio 2022 for MySQL, Version 9.1.21.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 12/02/2023 2:58:21 am
-- Server version: 10.4.27
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE gicalde_db;

--
-- Drop table `audit_trail`
--
DROP TABLE IF EXISTS audit_trail;

--
-- Drop table `cottages`
--
DROP TABLE IF EXISTS cottages;

--
-- Drop table `cottages_photos`
--
DROP TABLE IF EXISTS cottages_photos;

--
-- Drop table `galleries`
--
DROP TABLE IF EXISTS galleries;

--
-- Drop table `payment_details`
--
DROP TABLE IF EXISTS payment_details;

--
-- Drop table `reservations`
--
DROP TABLE IF EXISTS reservations;

--
-- Drop table `rooms`
--
DROP TABLE IF EXISTS rooms;

--
-- Drop table `room_photos`
--
DROP TABLE IF EXISTS room_photos;

--
-- Drop table `users`
--
DROP TABLE IF EXISTS users;

--
-- Set default database
--
USE gicalde_db;

--
-- Create table `users`
--
CREATE TABLE users (
  id int(11) NOT NULL AUTO_INCREMENT,
  code varchar(255) DEFAULT NULL,
  username varchar(255) DEFAULT NULL,
  password varchar(255) DEFAULT NULL,
  role_id int(11) DEFAULT NULL,
  activation_code varchar(255) DEFAULT NULL,
  first_name varchar(255) DEFAULT NULL,
  middle_name varchar(255) DEFAULT NULL,
  last_name varchar(255) DEFAULT NULL,
  dob date DEFAULT NULL,
  gender varchar(255) DEFAULT NULL,
  contact_no varchar(255) DEFAULT NULL,
  address varchar(255) DEFAULT NULL,
  is_activated int(1) DEFAULT NULL,
  created_by int(11) DEFAULT NULL,
  created_at datetime DEFAULT current_timestamp,
  updated_by int(11) DEFAULT NULL,
  updated_at datetime DEFAULT NULL,
  deleted_by int(11) DEFAULT NULL,
  deleted_at datetime DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 8,
AVG_ROW_LENGTH = 32768,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `room_photos`
--
CREATE TABLE room_photos (
  id int(11) NOT NULL AUTO_INCREMENT,
  room_id int(11) DEFAULT NULL,
  photo_key int(11) DEFAULT NULL,
  photo_file_name text DEFAULT NULL,
  created_by int(11) DEFAULT NULL,
  created_at datetime DEFAULT NULL,
  updated_by int(11) DEFAULT NULL,
  updated_at datetime DEFAULT NULL,
  deleted_by int(11) DEFAULT NULL,
  deleted_at datetime DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 17,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `rooms`
--
CREATE TABLE rooms (
  id int(11) NOT NULL AUTO_INCREMENT,
  name varchar(255) DEFAULT NULL,
  description text DEFAULT NULL,
  no_of_houses int(11) DEFAULT NULL,
  no_of_guests int(11) DEFAULT NULL,
  no_of_rooms int(11) DEFAULT NULL,
  price decimal(11, 2) DEFAULT NULL,
  slots int(11) DEFAULT NULL,
  created_by int(11) DEFAULT NULL,
  created_at datetime DEFAULT current_timestamp,
  updated_by int(11) DEFAULT NULL,
  updated_at datetime DEFAULT NULL,
  deleted_by int(11) DEFAULT NULL,
  deleted_at datetime DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 5,
AVG_ROW_LENGTH = 32768,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `reservations`
--
CREATE TABLE reservations (
  id int(11) NOT NULL AUTO_INCREMENT,
  room_id int(11) DEFAULT NULL,
  total_price decimal(11, 2) DEFAULT NULL,
  reference_no varchar(255) DEFAULT NULL,
  cottage_id int(11) DEFAULT NULL,
  check_in_date date DEFAULT NULL,
  check_out_date date DEFAULT NULL,
  no_of_guests int(11) DEFAULT NULL,
  mode_of_payment varchar(255) DEFAULT NULL,
  first_name varchar(255) DEFAULT NULL,
  middle_name varchar(255) DEFAULT NULL,
  last_name varchar(255) DEFAULT NULL,
  contact_no varchar(255) DEFAULT NULL,
  email_address varchar(255) DEFAULT NULL,
  address varchar(255) DEFAULT NULL,
  reservation_status int(11) DEFAULT NULL,
  paid_amount decimal(11, 2) DEFAULT 0.00,
  paid_date date DEFAULT NULL,
  payment_status int(11) DEFAULT NULL,
  created_by int(11) DEFAULT NULL,
  created_at datetime DEFAULT current_timestamp,
  updated_by int(11) DEFAULT NULL,
  updated_at datetime DEFAULT NULL,
  deleted_by int(11) DEFAULT NULL,
  deleted_at datetime DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `payment_details`
--
CREATE TABLE payment_details (
  id int(11) NOT NULL AUTO_INCREMENT,
  gcash_name varchar(255) DEFAULT NULL,
  gcash_account_number varchar(255) DEFAULT NULL,
  bank_account_name varchar(255) DEFAULT NULL,
  bank_account_number varchar(255) DEFAULT NULL,
  created_by int(11) DEFAULT NULL,
  created_at datetime DEFAULT current_timestamp,
  updated_by int(11) DEFAULT NULL,
  updated_at datetime DEFAULT NULL,
  deleted_by int(11) DEFAULT NULL,
  deleted_at datetime DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `galleries`
--
CREATE TABLE galleries (
  id int(11) NOT NULL AUTO_INCREMENT,
  photo_file_name varchar(255) DEFAULT NULL,
  created_by int(11) DEFAULT NULL,
  created_at datetime DEFAULT current_timestamp,
  updated_by int(11) DEFAULT NULL,
  updated_at datetime DEFAULT NULL,
  deleted_by int(11) DEFAULT NULL,
  deleted_at datetime DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `cottages_photos`
--
CREATE TABLE cottages_photos (
  id int(11) NOT NULL AUTO_INCREMENT,
  cottages_id int(11) DEFAULT NULL,
  photo_key int(11) DEFAULT NULL,
  photo_file_name varchar(255) DEFAULT NULL,
  created_by int(11) DEFAULT NULL,
  created_at datetime DEFAULT NULL,
  updated_by int(11) DEFAULT NULL,
  updated_at datetime DEFAULT NULL,
  deleted_by int(11) DEFAULT NULL,
  deleted_at datetime DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `cottages`
--
CREATE TABLE cottages (
  id int(11) NOT NULL AUTO_INCREMENT,
  name varchar(255) DEFAULT NULL,
  description text DEFAULT NULL,
  no_of_guests int(11) DEFAULT 0,
  price decimal(11, 2) DEFAULT 0.00,
  slots int(11) DEFAULT 0,
  created_by int(11) DEFAULT NULL,
  created_at datetime DEFAULT current_timestamp,
  updated_by int(11) DEFAULT NULL,
  updated_at datetime DEFAULT NULL,
  deleted_by int(11) DEFAULT NULL,
  deleted_at datetime DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 8,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `audit_trail`
--
CREATE TABLE audit_trail (
  id int(11) NOT NULL AUTO_INCREMENT,
  email_address varchar(255) DEFAULT NULL,
  action_taken text DEFAULT NULL,
  created_by int(11) DEFAULT NULL,
  created_at datetime DEFAULT current_timestamp,
  updated_by int(11) DEFAULT NULL,
  updated_at datetime DEFAULT NULL,
  deleted_by int(11) DEFAULT NULL,
  deleted_at datetime DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

-- 
-- Dumping data for table users
--
INSERT INTO users VALUES
(1, '1', 'admin@mail.com', '$2y$10$syv23bvpa0ujAz6Piz5Ob.QEfuG8kKv43fthNKwBJgkj2NZ8nAuvK', 1, NULL, 'ADMINISTRATOR', NULL, 'ADMINISTRATOR', '2023-01-20', 'MALE', '09958242310', 'ROXAS CITY, CAPIZ', 1, 1, '2023-01-20 07:26:23', NULL, NULL, NULL, NULL);

-- 
-- Dumping data for table room_photos
--
INSERT INTO room_photos VALUES
(1, 1, 0, '2.jpg', 1, '2023-01-22 06:08:20', NULL, NULL, NULL, NULL);

-- 
-- Dumping data for table rooms
--
INSERT INTO rooms VALUES
(1, 'BUNGALOW HOUSE', '24 Hours Stay in.', 1, 8, 2, 4000.00, 0, 1, '2023-01-22 06:08:20', 1, '2023-01-23 01:26:57', NULL, NULL);

-- 
-- Dumping data for table reservations
--
-- Table gicalde_db.reservations does not contain any data (it is empty)

-- 
-- Dumping data for table payment_details
--
INSERT INTO payment_details VALUES
(1, 'JUAN DELA CRUZ', '09958242310', 'N/A', 'N/A', 1, '2023-01-22 00:00:00', 1, '2023-01-23 05:03:58', NULL, NULL);

-- 
-- Dumping data for table galleries
--
INSERT INTO galleries VALUES
(1, '4893f105d8b36cbba45811e25f5712c2.jpg', 1, '2023-02-12 02:57:03', NULL, NULL, NULL, NULL),
(2, 'ece82ed5b2f8b0513e0817b15fe91edf.jpg', 1, '2023-02-12 02:57:08', NULL, NULL, NULL, NULL),
(3, 'eb1e4893cd783284c4dd6287d17af6a1.jpg', 1, '2023-02-12 02:57:12', NULL, NULL, NULL, NULL);

-- 
-- Dumping data for table cottages_photos
--
INSERT INTO cottages_photos VALUES
(1, 5, 0, '15efc28cbd6cbf99a793ddaf752040a3.jpg', 1, '2023-01-22 10:55:53', 1, '2023-01-22 10:57:13', NULL, NULL),
(2, 6, 0, '630eeec626530c97ec2cd700b89eac8f.jpg', 1, '2023-01-22 11:32:29', NULL, NULL, NULL, NULL),
(3, 7, 0, 'd419980f94ec13388f507076847e7264.jpg', 1, '2023-01-22 11:33:05', NULL, NULL, NULL, NULL);

-- 
-- Dumping data for table cottages
--
INSERT INTO cottages VALUES
(5, 'CABANA', '8:00AM - 5:00PM', 10, 700.00, 5, 1, '2023-01-22 10:45:48', 1, '2023-01-22 10:58:28', NULL, NULL),
(6, 'COTTAGE', '8:00AM - 5:00 PM', 10, 300.00, 4, 1, '2023-01-22 11:32:29', 1, '2023-01-23 04:52:04', NULL, NULL),
(7, 'EVENT VENUE', '8:00AM - 5:00PM', 20, 4000.00, 10, 1, '2023-01-22 11:33:05', NULL, NULL, NULL, NULL);

-- 
-- Dumping data for table audit_trail
--
-- Table gicalde_db.audit_trail does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;