--
-- Script was generated by Devart dbForge Studio 2022 for MySQL, Version 9.1.21.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 05/03/2023 10:54:39 pm
-- Server version: 10.4.27
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE gicalde_db;

--
-- Drop table `audit_trail`
--
DROP TABLE IF EXISTS audit_trail;

--
-- Drop table `cottages`
--
DROP TABLE IF EXISTS cottages;

--
-- Drop table `cottages_photos`
--
DROP TABLE IF EXISTS cottages_photos;

--
-- Drop table `galleries`
--
DROP TABLE IF EXISTS galleries;

--
-- Drop table `payment_details`
--
DROP TABLE IF EXISTS payment_details;

--
-- Drop table `reservations`
--
DROP TABLE IF EXISTS reservations;

--
-- Drop table `rooms`
--
DROP TABLE IF EXISTS rooms;

--
-- Drop table `room_photos`
--
DROP TABLE IF EXISTS room_photos;

--
-- Drop table `users`
--
DROP TABLE IF EXISTS users;

--
-- Set default database
--
USE gicalde_db;

--
-- Create table `users`
--
CREATE TABLE users (
  id int(11) NOT NULL AUTO_INCREMENT,
  code varchar(255) DEFAULT NULL,
  username varchar(255) DEFAULT NULL,
  password varchar(255) DEFAULT NULL,
  role_id int(11) DEFAULT NULL,
  activation_code varchar(255) DEFAULT NULL,
  first_name varchar(255) DEFAULT NULL,
  middle_name varchar(255) DEFAULT NULL,
  last_name varchar(255) DEFAULT NULL,
  dob date DEFAULT NULL,
  gender varchar(255) DEFAULT NULL,
  contact_no varchar(255) DEFAULT NULL,
  address varchar(255) DEFAULT NULL,
  is_activated int(1) DEFAULT NULL,
  created_by int(11) DEFAULT NULL,
  created_at datetime DEFAULT current_timestamp,
  updated_by int(11) DEFAULT NULL,
  updated_at datetime DEFAULT NULL,
  deleted_by int(11) DEFAULT NULL,
  deleted_at datetime DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 9,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `room_photos`
--
CREATE TABLE room_photos (
  id int(11) NOT NULL AUTO_INCREMENT,
  room_id int(11) DEFAULT NULL,
  photo_key int(11) DEFAULT NULL,
  photo_file_name text DEFAULT NULL,
  created_by int(11) DEFAULT NULL,
  created_at datetime DEFAULT NULL,
  updated_by int(11) DEFAULT NULL,
  updated_at datetime DEFAULT NULL,
  deleted_by int(11) DEFAULT NULL,
  deleted_at datetime DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `rooms`
--
CREATE TABLE rooms (
  id int(11) NOT NULL AUTO_INCREMENT,
  name varchar(255) DEFAULT NULL,
  description text DEFAULT NULL,
  no_of_houses int(11) DEFAULT NULL,
  no_of_guests int(11) DEFAULT NULL,
  no_of_rooms int(11) DEFAULT NULL,
  price decimal(11, 2) DEFAULT NULL,
  slots int(11) DEFAULT NULL,
  created_by int(11) DEFAULT NULL,
  created_at datetime DEFAULT current_timestamp,
  updated_by int(11) DEFAULT NULL,
  updated_at datetime DEFAULT NULL,
  deleted_by int(11) DEFAULT NULL,
  deleted_at datetime DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `reservations`
--
CREATE TABLE reservations (
  id int(11) NOT NULL AUTO_INCREMENT,
  room_id int(11) DEFAULT NULL,
  total_price decimal(11, 2) DEFAULT NULL,
  reference_no varchar(255) DEFAULT NULL,
  cottage_id int(11) DEFAULT NULL,
  check_in_date date DEFAULT NULL,
  check_out_date date DEFAULT NULL,
  no_of_guests int(11) DEFAULT NULL,
  mode_of_payment varchar(255) DEFAULT NULL,
  first_name varchar(255) DEFAULT NULL,
  middle_name varchar(255) DEFAULT NULL,
  last_name varchar(255) DEFAULT NULL,
  contact_no varchar(255) DEFAULT NULL,
  email_address varchar(255) DEFAULT NULL,
  address varchar(255) DEFAULT NULL,
  reservation_status int(11) DEFAULT NULL,
  paid_amount decimal(11, 2) DEFAULT 0.00,
  paid_date date DEFAULT NULL,
  payment_status int(11) DEFAULT NULL,
  created_by int(11) DEFAULT NULL,
  created_at datetime DEFAULT current_timestamp,
  updated_by int(11) DEFAULT NULL,
  updated_at datetime DEFAULT NULL,
  deleted_by int(11) DEFAULT NULL,
  deleted_at datetime DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `payment_details`
--
CREATE TABLE payment_details (
  id int(11) NOT NULL AUTO_INCREMENT,
  gcash_name varchar(255) DEFAULT NULL,
  gcash_account_number varchar(255) DEFAULT NULL,
  bank_account_name varchar(255) DEFAULT NULL,
  bank_account_number varchar(255) DEFAULT NULL,
  created_by int(11) DEFAULT NULL,
  created_at datetime DEFAULT current_timestamp,
  updated_by int(11) DEFAULT NULL,
  updated_at datetime DEFAULT NULL,
  deleted_by int(11) DEFAULT NULL,
  deleted_at datetime DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `galleries`
--
CREATE TABLE galleries (
  id int(11) NOT NULL AUTO_INCREMENT,
  photo_file_name varchar(255) DEFAULT NULL,
  created_by int(11) DEFAULT NULL,
  created_at datetime DEFAULT current_timestamp,
  updated_by int(11) DEFAULT NULL,
  updated_at datetime DEFAULT NULL,
  deleted_by int(11) DEFAULT NULL,
  deleted_at datetime DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `cottages_photos`
--
CREATE TABLE cottages_photos (
  id int(11) NOT NULL AUTO_INCREMENT,
  cottages_id int(11) DEFAULT NULL,
  photo_key int(11) DEFAULT NULL,
  photo_file_name varchar(255) DEFAULT NULL,
  created_by int(11) DEFAULT NULL,
  created_at datetime DEFAULT NULL,
  updated_by int(11) DEFAULT NULL,
  updated_at datetime DEFAULT NULL,
  deleted_by int(11) DEFAULT NULL,
  deleted_at datetime DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `cottages`
--
CREATE TABLE cottages (
  id int(11) NOT NULL AUTO_INCREMENT,
  name varchar(255) DEFAULT NULL,
  description text DEFAULT NULL,
  no_of_guests int(11) DEFAULT 0,
  price decimal(11, 2) DEFAULT 0.00,
  slots int(11) DEFAULT 0,
  created_by int(11) DEFAULT NULL,
  created_at datetime DEFAULT current_timestamp,
  updated_by int(11) DEFAULT NULL,
  updated_at datetime DEFAULT NULL,
  deleted_by int(11) DEFAULT NULL,
  deleted_at datetime DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `audit_trail`
--
CREATE TABLE audit_trail (
  id int(11) NOT NULL AUTO_INCREMENT,
  email_address varchar(255) DEFAULT NULL,
  action_taken text DEFAULT NULL,
  created_by int(11) DEFAULT NULL,
  created_at datetime DEFAULT current_timestamp,
  updated_by int(11) DEFAULT NULL,
  updated_at datetime DEFAULT NULL,
  deleted_by int(11) DEFAULT NULL,
  deleted_at datetime DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

-- 
-- Dumping data for table users
--
INSERT INTO users VALUES
(1, '1', 'admin@mail.com', '$2y$10$syv23bvpa0ujAz6Piz5Ob.QEfuG8kKv43fthNKwBJgkj2NZ8nAuvK', 1, NULL, 'ADMINISTRATOR', NULL, 'ADMINISTRATOR', '2023-01-20', 'MALE', '09958242310', 'ROXAS CITY, CAPIZ', 1, 1, '2023-01-20 07:26:23', NULL, NULL, NULL, NULL);

-- 
-- Dumping data for table room_photos
--
-- Table gicalde_db.room_photos does not contain any data (it is empty)

-- 
-- Dumping data for table rooms
--
-- Table gicalde_db.rooms does not contain any data (it is empty)

-- 
-- Dumping data for table reservations
--
INSERT INTO reservations VALUES
(1, 1, 4000.00, 'GICALDE2023-JBR7XLJJDC', NULL, '2023-02-26', '2023-03-02', 8, 'GCASH', 'KEEN DAVID', '', 'AGURO', '09958242310', 'agurokeendavid@gmail.com', 'MANILA', 3, 4000.00, '2023-02-26', 1, 1, '2023-02-26 19:54:00', 1, '2023-02-26 19:57:00', NULL, NULL);

-- 
-- Dumping data for table payment_details
--
INSERT INTO payment_details VALUES
(1, 'JUAN DELA CRUZ', '09958242310', 'N/A', 'N/A', 1, '2023-01-22 00:00:00', 1, '2023-01-23 05:03:58', NULL, NULL);

-- 
-- Dumping data for table galleries
--
-- Table gicalde_db.galleries does not contain any data (it is empty)

-- 
-- Dumping data for table cottages_photos
--
-- Table gicalde_db.cottages_photos does not contain any data (it is empty)

-- 
-- Dumping data for table cottages
--
-- Table gicalde_db.cottages does not contain any data (it is empty)

-- 
-- Dumping data for table audit_trail
--
-- Table gicalde_db.audit_trail does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;